apiVersion: v1
kind: Service
metadata:
  name: {{ include "gprox.fullname" . }}
  namespace: {{ include "gprox.namespace" . }}
  labels:
    {{- include "gprox.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $metricsPort := default (printf "%v" .Values.service.port) .Values.metrics.port }}
  {{- if or .Values.metrics.enabled .Values.service.annotations }}
  annotations:
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ (.Values.metrics.path | default "/metrics") | quote }}
    prometheus.io/port: {{ $metricsPort | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "gprox.selectorLabels" . | nindent 4 }}
