# Example values for production deployment
replicaCount: 1

image:
  repository: metabase/metabase
  pullPolicy: IfNotPresent
  tag: "v0.56.6.x"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: metabase.yourdomain.com  # Change this to your domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: metabase-tls
      hosts:
        - metabase.yourdomain.com  # Change this to your domain

# For production, consider using PostgreSQL
database:
  type: postgresql
  postgresql:
    host: postgresql.database.svc.cluster.local  # Change to your PostgreSQL host
    port: 5432
    database: metabase
    username: metabase
    existingSecret: metabase-db-secret  # Create this secret with your DB password
    secretKey: password

persistence:
  enabled: true
  storageClass: ""  # Use default storage class or specify your preferred one
  size: 20Gi  # Increased for production

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

metabase:
  siteUrl: "https://metabase.yourdomain.com"  # Change this to your domain
  javaOpts: "-Xmx2g"
  timezone: "America/New_York"  # Change to your timezone

# Optional: Set up admin user (remove after first login)
# metabase:
#   admin:
#     email: admin@yourdomain.com
#     password: changeme123
#     firstName: "Admin"
#     lastName: "User"
