apiVersion: v2
name: gprox
description: ACME DNS proxy for Google Cloud DNS packaged for Kubernetes.
type: application
version: 0.1.3
appVersion: "0.1.2"
kubeVersion: ">=1.26.0-0"
keywords:
  - acme
  - dns
  - google-cloud-dns
  - proxy
  - certificates
home: https://github.com/rioncm/charts
sources:
  - https://github.com/rioncm/charts/tree/main/_dev/gprox
maintainers:
  - name: rion
    email: rioncm@gmail.com
