apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
---
{{- if ne .Values.internalHostname "" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.internalHostname }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
    service-type: internal
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
{{- end }}
