{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" (include "odoo-cs.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "odoo-cs.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{ toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
