# Default values for the simplified Outline chart.
# Declare variables to be passed into your templates.

namespace: outline-project

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: outlinewiki/outline
  tag: "0.87.4"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

service:
  type: ClusterIP
  port: 3000
  annotations: {}
  labels: {}
  nodePort: null

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: docs.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: outline-tls
      hosts:
        - docs.example.com

outline:
  url: "https://docs.example.com"
  collaborationUrl: ""
  cdnUrl: ""
  webConcurrency: 1
  defaultLanguage: en_US
  forceHttps: true
  enableUpdates: true
  debug: http
  logLevel: info

secrets:
  existingSecret: ""

# Outline requires DATABASE_URL, SECRET_KEY, and UTILS_SECRET to be supplied via existing secrets.
database:
  initialize: true
  url: ""
  existingSecret: ""
  existingSecretKey: DATABASE_URL
  sslMode: require
  connectionPool:
    min: ""
    max: ""

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  externalUrl: ""

fileStorage:
  type: local
  localRootDir: /var/lib/outline/data
  uploadMaxSize: 262144000
  importMaxSize: ""
  workspaceImportMaxSize: ""
  s3:
    region: ""
    accessKeyId: ""
    secretAccessKey: ""
    accelerateUrl: ""
    uploadBucketUrl: ""
    uploadBucketName: ""
    forcePathStyle: true
    acl: private

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  existingClaim: ""

rateLimiter:
  enabled: true
  requests: 1000
  durationWindow: 60

extraEnv: []
extraEnvFrom: []
extraVolumeMounts: []
extraVolumes: []

nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""

livenessProbe:
  enabled: true
  httpGet:
    path: /_health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /_health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3